version: '3'
services:
  web:
    image: smileahappysmile/university-scheduling
    build: .
    ports:
      - 8080:8080
    environment:
        NODE_APP_PORT: 8080
        MONGODB_HOST: "mongodatabase1"
        MONGODB_USER: "mongodb_user1234"
        MONGODB_PASSWORD: "34ct873b7y4394rmy43"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: "mongodatabase1"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    ports:
      - "27017:27017"
    volumes:
      - /data:/data/db
      - ./db/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
