version: '3'
services:
  web:
    image: smileahappysmile/university-scheduling
    deploy:
      replicas: 4
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s
    networks: 
     - balance 
    ports:
      - 8080:8080
    environment:
        NODE_APP_PORT: 8080
        MONGODB_HOST: "mongo"
        MONGODB_USER: "mongodb_user1234"
        MONGODB_PASSWORD: "34ct873b7y4394rmy43"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    ports:
      - "27017:27017"
    networks: 
      - balance
    volumes:
      - /data/db:/data/db
      - ./db/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  proxy:
    image: nginx:1.15-alpine
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /data/nginx:/etc/nginx/conf.d
      - /data/certbot/conf:/etc/letsencrypt
    networks: 
      - balance
networks:
  balance:
    driver: overlay
